# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/khtb/workset/c_parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/khtb/workset/c_parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/khtb/workset/c_parser/CMakeFiles /Users/khtb/workset/c_parser//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/khtb/workset/c_parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TinyXML2

# Build rule for target.
TinyXML2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TinyXML2
.PHONY : TinyXML2

# fast build rule for target.
TinyXML2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TinyXML2.dir/build.make CMakeFiles/TinyXML2.dir/build
.PHONY : TinyXML2/fast

#=============================================================================
# Target rules for targets named ParseCFile

# Build rule for target.
ParseCFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ParseCFile
.PHONY : ParseCFile

# fast build rule for target.
ParseCFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/build
.PHONY : ParseCFile/fast

#=============================================================================
# Target rules for targets named string_util

# Build rule for target.
string_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 string_util
.PHONY : string_util

# fast build rule for target.
string_util/fast:
	$(MAKE) $(MAKESILENT) -f libs/string_util/CMakeFiles/string_util.dir/build.make libs/string_util/CMakeFiles/string_util.dir/build
.PHONY : string_util/fast

src/core_cli/IApplication.o: src/core_cli/IApplication.cpp.o
.PHONY : src/core_cli/IApplication.o

# target to build an object file
src/core_cli/IApplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/IApplication.cpp.o
.PHONY : src/core_cli/IApplication.cpp.o

src/core_cli/IApplication.i: src/core_cli/IApplication.cpp.i
.PHONY : src/core_cli/IApplication.i

# target to preprocess a source file
src/core_cli/IApplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/IApplication.cpp.i
.PHONY : src/core_cli/IApplication.cpp.i

src/core_cli/IApplication.s: src/core_cli/IApplication.cpp.s
.PHONY : src/core_cli/IApplication.s

# target to generate assembly for a file
src/core_cli/IApplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/IApplication.cpp.s
.PHONY : src/core_cli/IApplication.cpp.s

src/core_cli/core_cli.o: src/core_cli/core_cli.cpp.o
.PHONY : src/core_cli/core_cli.o

# target to build an object file
src/core_cli/core_cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/core_cli.cpp.o
.PHONY : src/core_cli/core_cli.cpp.o

src/core_cli/core_cli.i: src/core_cli/core_cli.cpp.i
.PHONY : src/core_cli/core_cli.i

# target to preprocess a source file
src/core_cli/core_cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/core_cli.cpp.i
.PHONY : src/core_cli/core_cli.cpp.i

src/core_cli/core_cli.s: src/core_cli/core_cli.cpp.s
.PHONY : src/core_cli/core_cli.s

# target to generate assembly for a file
src/core_cli/core_cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/core_cli.cpp.s
.PHONY : src/core_cli/core_cli.cpp.s

src/core_cli/mainApp.o: src/core_cli/mainApp.cpp.o
.PHONY : src/core_cli/mainApp.o

# target to build an object file
src/core_cli/mainApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/mainApp.cpp.o
.PHONY : src/core_cli/mainApp.cpp.o

src/core_cli/mainApp.i: src/core_cli/mainApp.cpp.i
.PHONY : src/core_cli/mainApp.i

# target to preprocess a source file
src/core_cli/mainApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/mainApp.cpp.i
.PHONY : src/core_cli/mainApp.cpp.i

src/core_cli/mainApp.s: src/core_cli/mainApp.cpp.s
.PHONY : src/core_cli/mainApp.s

# target to generate assembly for a file
src/core_cli/mainApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/mainApp.cpp.s
.PHONY : src/core_cli/mainApp.cpp.s

src/core_cli/misc.o: src/core_cli/misc.cpp.o
.PHONY : src/core_cli/misc.o

# target to build an object file
src/core_cli/misc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/misc.cpp.o
.PHONY : src/core_cli/misc.cpp.o

src/core_cli/misc.i: src/core_cli/misc.cpp.i
.PHONY : src/core_cli/misc.i

# target to preprocess a source file
src/core_cli/misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/misc.cpp.i
.PHONY : src/core_cli/misc.cpp.i

src/core_cli/misc.s: src/core_cli/misc.cpp.s
.PHONY : src/core_cli/misc.s

# target to generate assembly for a file
src/core_cli/misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/core_cli/misc.cpp.s
.PHONY : src/core_cli/misc.cpp.s

src/file/FileScanner.o: src/file/FileScanner.cpp.o
.PHONY : src/file/FileScanner.o

# target to build an object file
src/file/FileScanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/file/FileScanner.cpp.o
.PHONY : src/file/FileScanner.cpp.o

src/file/FileScanner.i: src/file/FileScanner.cpp.i
.PHONY : src/file/FileScanner.i

# target to preprocess a source file
src/file/FileScanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/file/FileScanner.cpp.i
.PHONY : src/file/FileScanner.cpp.i

src/file/FileScanner.s: src/file/FileScanner.cpp.s
.PHONY : src/file/FileScanner.s

# target to generate assembly for a file
src/file/FileScanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/file/FileScanner.cpp.s
.PHONY : src/file/FileScanner.cpp.s

src/main/main.o: src/main/main.cpp.o
.PHONY : src/main/main.o

# target to build an object file
src/main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/main/main.cpp.o
.PHONY : src/main/main.cpp.o

src/main/main.i: src/main/main.cpp.i
.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/main/main.cpp.i
.PHONY : src/main/main.cpp.i

src/main/main.s: src/main/main.cpp.s
.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/main/main.cpp.s
.PHONY : src/main/main.cpp.s

src/mod1/mod1.o: src/mod1/mod1.cpp.o
.PHONY : src/mod1/mod1.o

# target to build an object file
src/mod1/mod1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/mod1/mod1.cpp.o
.PHONY : src/mod1/mod1.cpp.o

src/mod1/mod1.i: src/mod1/mod1.cpp.i
.PHONY : src/mod1/mod1.i

# target to preprocess a source file
src/mod1/mod1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/mod1/mod1.cpp.i
.PHONY : src/mod1/mod1.cpp.i

src/mod1/mod1.s: src/mod1/mod1.cpp.s
.PHONY : src/mod1/mod1.s

# target to generate assembly for a file
src/mod1/mod1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/mod1/mod1.cpp.s
.PHONY : src/mod1/mod1.cpp.s

src/mod2/mod2.o: src/mod2/mod2.cpp.o
.PHONY : src/mod2/mod2.o

# target to build an object file
src/mod2/mod2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/mod2/mod2.cpp.o
.PHONY : src/mod2/mod2.cpp.o

src/mod2/mod2.i: src/mod2/mod2.cpp.i
.PHONY : src/mod2/mod2.i

# target to preprocess a source file
src/mod2/mod2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/mod2/mod2.cpp.i
.PHONY : src/mod2/mod2.cpp.i

src/mod2/mod2.s: src/mod2/mod2.cpp.s
.PHONY : src/mod2/mod2.s

# target to generate assembly for a file
src/mod2/mod2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/mod2/mod2.cpp.s
.PHONY : src/mod2/mod2.cpp.s

src/network/net_IApp.o: src/network/net_IApp.cpp.o
.PHONY : src/network/net_IApp.o

# target to build an object file
src/network/net_IApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/network/net_IApp.cpp.o
.PHONY : src/network/net_IApp.cpp.o

src/network/net_IApp.i: src/network/net_IApp.cpp.i
.PHONY : src/network/net_IApp.i

# target to preprocess a source file
src/network/net_IApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/network/net_IApp.cpp.i
.PHONY : src/network/net_IApp.cpp.i

src/network/net_IApp.s: src/network/net_IApp.cpp.s
.PHONY : src/network/net_IApp.s

# target to generate assembly for a file
src/network/net_IApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/network/net_IApp.cpp.s
.PHONY : src/network/net_IApp.cpp.s

src/svd_parser/svdParser.o: src/svd_parser/svdParser.cpp.o
.PHONY : src/svd_parser/svdParser.o

# target to build an object file
src/svd_parser/svdParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/svd_parser/svdParser.cpp.o
.PHONY : src/svd_parser/svdParser.cpp.o

src/svd_parser/svdParser.i: src/svd_parser/svdParser.cpp.i
.PHONY : src/svd_parser/svdParser.i

# target to preprocess a source file
src/svd_parser/svdParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/svd_parser/svdParser.cpp.i
.PHONY : src/svd_parser/svdParser.cpp.i

src/svd_parser/svdParser.s: src/svd_parser/svdParser.cpp.s
.PHONY : src/svd_parser/svdParser.s

# target to generate assembly for a file
src/svd_parser/svdParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/svd_parser/svdParser.cpp.s
.PHONY : src/svd_parser/svdParser.cpp.s

src/svd_parser/svdParser_IApp.o: src/svd_parser/svdParser_IApp.cpp.o
.PHONY : src/svd_parser/svdParser_IApp.o

# target to build an object file
src/svd_parser/svdParser_IApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/svd_parser/svdParser_IApp.cpp.o
.PHONY : src/svd_parser/svdParser_IApp.cpp.o

src/svd_parser/svdParser_IApp.i: src/svd_parser/svdParser_IApp.cpp.i
.PHONY : src/svd_parser/svdParser_IApp.i

# target to preprocess a source file
src/svd_parser/svdParser_IApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/svd_parser/svdParser_IApp.cpp.i
.PHONY : src/svd_parser/svdParser_IApp.cpp.i

src/svd_parser/svdParser_IApp.s: src/svd_parser/svdParser_IApp.cpp.s
.PHONY : src/svd_parser/svdParser_IApp.s

# target to generate assembly for a file
src/svd_parser/svdParser_IApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/svd_parser/svdParser_IApp.cpp.s
.PHONY : src/svd_parser/svdParser_IApp.cpp.s

src/tinyxml2/tinyxml2.o: src/tinyxml2/tinyxml2.cpp.o
.PHONY : src/tinyxml2/tinyxml2.o

# target to build an object file
src/tinyxml2/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TinyXML2.dir/build.make CMakeFiles/TinyXML2.dir/src/tinyxml2/tinyxml2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/tinyxml2/tinyxml2.cpp.o
.PHONY : src/tinyxml2/tinyxml2.cpp.o

src/tinyxml2/tinyxml2.i: src/tinyxml2/tinyxml2.cpp.i
.PHONY : src/tinyxml2/tinyxml2.i

# target to preprocess a source file
src/tinyxml2/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TinyXML2.dir/build.make CMakeFiles/TinyXML2.dir/src/tinyxml2/tinyxml2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/tinyxml2/tinyxml2.cpp.i
.PHONY : src/tinyxml2/tinyxml2.cpp.i

src/tinyxml2/tinyxml2.s: src/tinyxml2/tinyxml2.cpp.s
.PHONY : src/tinyxml2/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TinyXML2.dir/build.make CMakeFiles/TinyXML2.dir/src/tinyxml2/tinyxml2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ParseCFile.dir/build.make CMakeFiles/ParseCFile.dir/src/tinyxml2/tinyxml2.cpp.s
.PHONY : src/tinyxml2/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ParseCFile"
	@echo "... TinyXML2"
	@echo "... string_util"
	@echo "... src/core_cli/IApplication.o"
	@echo "... src/core_cli/IApplication.i"
	@echo "... src/core_cli/IApplication.s"
	@echo "... src/core_cli/core_cli.o"
	@echo "... src/core_cli/core_cli.i"
	@echo "... src/core_cli/core_cli.s"
	@echo "... src/core_cli/mainApp.o"
	@echo "... src/core_cli/mainApp.i"
	@echo "... src/core_cli/mainApp.s"
	@echo "... src/core_cli/misc.o"
	@echo "... src/core_cli/misc.i"
	@echo "... src/core_cli/misc.s"
	@echo "... src/file/FileScanner.o"
	@echo "... src/file/FileScanner.i"
	@echo "... src/file/FileScanner.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
	@echo "... src/mod1/mod1.o"
	@echo "... src/mod1/mod1.i"
	@echo "... src/mod1/mod1.s"
	@echo "... src/mod2/mod2.o"
	@echo "... src/mod2/mod2.i"
	@echo "... src/mod2/mod2.s"
	@echo "... src/network/net_IApp.o"
	@echo "... src/network/net_IApp.i"
	@echo "... src/network/net_IApp.s"
	@echo "... src/svd_parser/svdParser.o"
	@echo "... src/svd_parser/svdParser.i"
	@echo "... src/svd_parser/svdParser.s"
	@echo "... src/svd_parser/svdParser_IApp.o"
	@echo "... src/svd_parser/svdParser_IApp.i"
	@echo "... src/svd_parser/svdParser_IApp.s"
	@echo "... src/tinyxml2/tinyxml2.o"
	@echo "... src/tinyxml2/tinyxml2.i"
	@echo "... src/tinyxml2/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

